name: Hello world workflow

on:
  push: main
  pull: main
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    -name:
     run: echo "Hello World"
     
  goodbye:
    runs-on: ubuntu-latest
    steps:
    -name:
     run: echo "Goodbye World"
